# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('phone_number_verify_time', models.DateTimeField()),
                ('wx_openid', models.CharField(max_length=20)),
                ('wx_openid_verify_time', models.DateTimeField()),
                ('qq_openid', models.CharField(max_length=20)),
                ('qq_openid_verify_time', models.DateTimeField()),
                ('weibo_openid', models.CharField(max_length=20)),
                ('weibo_openid_verify_time', models.DateTimeField()),
                ('email', models.CharField(max_length=40)),
                ('email_verify_time', models.DateTimeField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=20)),
                ('nick', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('portrait', models.CharField(max_length=40)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileExt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=40)),
                ('nation', models.CharField(max_length=20)),
                ('blood_type', models.CharField(max_length=3)),
                ('birthday', models.DateField()),
                ('certificate_no', models.CharField(max_length=40)),
                ('street', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='bind',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Profile'),
        ),
    ]
