# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0002_conversation_job_mergemsg_share_vipjoblist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vipjoblist',
            name='id',
        ),
        migrations.AlterField(
            model_name='vipjoblist',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
